### ISSUE TITLE
Blinking pin on input only there in poly app on v2.3002.1 

### ISSUE THREAD

**Issue by johncresonII** [Zondax/ledger-polymesh#70]
I'm testing the lite app on nano s - and once that app is installed and running, pin input is now blinking on every button push. Blinking and pulsing through the line of empty characters. When NOT in app, there was no blinking of the pin input when in app, there is - which also now has up and down arrows - which is weird to me now that I think they mean right and left sliding - up and down arrows also leave less room for reading the words on the screen.

**Comment by jleni** [comment]
Just to clarify. You need to enter the PIN because yo let the app loaded
and then you waited for device to lock?

We don't have control over PIN input.. that is at the OS level... But I
wonder if there is something different in the current Ledger OS/firmware
that results in this to happen..

This is a very interesting finding.. and I am not sure why the screen is
actually different...

**Comment by johncresonII** [comment]
I needed to enter the pin because I was doing something, authorizing something that was going to involve sending POLYX or incurring a fee in POLYX. It may have been a timing issue as well, because after first entering the pin for that, I often get to just sign on the ledger without refresh as long as the ledger hasn't timed out and started its screen-saver.

Do you need a video of what it is doing?

**Comment by Neopallium** [comment]
I sent a video to the Zondax slack channel.
